export type CardCategory = "couple" | "birthday" | "pet";

export type AiLocation = {
  id: string;
  name: string;
  country: string;
  emoji: string;
  region: string;
  promptHint: string;
  textStyle: string;
  categories: CardCategory[]; // which card types this location is available for
};

export const AI_LOCATIONS: AiLocation[] = [
  // ── Mediterranean ──────────────────────────────────────────────────────────
  { id: "ibiza-beach", name: "Ibiza Beach", country: "Spain", emoji: "🏖️", region: "Mediterranean",
    categories: ["couple", "birthday"],
    promptHint: "sun-drenched white sandy beach in Ibiza, Spain, crystal clear turquoise Mediterranean water, luxury beach clubs, golden cliffs, vivid blue sky",
    textStyle: "written in large elegant letters in the wet sand near the water's edge" },
  { id: "santorini", name: "Santorini", country: "Greece", emoji: "🇬🇷", region: "Mediterranean",
    categories: ["couple", "birthday"],
    promptHint: "iconic white-washed buildings with blue domed churches in Santorini, Greece, dramatic caldera cliffs, deep blue Aegean Sea, spectacular sunset sky",
    textStyle: "painted in white on a blue-domed wall in flowing script" },
  { id: "amalfi-coast", name: "Amalfi Coast", country: "Italy", emoji: "🍋", region: "Mediterranean",
    categories: ["couple", "birthday"],
    promptHint: "dramatic Amalfi Coast cliffs in Italy, colorful cliffside villages, shimmering turquoise Mediterranean, lemon groves, winding coastal roads",
    textStyle: "on a hand-painted ceramic sign hanging among lemon branches on the cliff wall" },
  { id: "cinque-terre", name: "Cinque Terre", country: "Italy", emoji: "🌊", region: "Mediterranean",
    categories: ["couple"],
    promptHint: "pastel-colored fishing village of Cinque Terre, Italy, perched on rugged cliffs above the Ligurian Sea, terraced vineyards, charming harbor",
    textStyle: "painted on the colorful hull of a fishing boat in the harbor" },
  { id: "mykonos", name: "Mykonos", country: "Greece", emoji: "🌞", region: "Mediterranean",
    categories: ["couple"],
    promptHint: "whitewashed cycladic architecture in Mykonos, Greece, famous windmills, cobblestone streets with bougainvillea, brilliant blue Aegean Sea",
    textStyle: "painted in vibrant blue on a whitewashed wall beside purple bougainvillea" },
  { id: "capri", name: "Capri Island", country: "Italy", emoji: "⛵", region: "Mediterranean",
    categories: ["couple", "birthday"],
    promptHint: "glamorous Capri island, Italy, natural sea arch Faraglioni rocks, emerald Blue Grotto waters, luxury yachts, Mediterranean gardens, panoramic cliffs",
    textStyle: "in gold lettering on the bow of a luxury yacht" },
  { id: "positano", name: "Positano", country: "Italy", emoji: "🌺", region: "Mediterranean",
    categories: ["couple"],
    promptHint: "romantic village of Positano cascading down steep cliffs, pastel colored buildings, bougainvillea flowers, pebble beach, turquoise Tyrrhenian Sea",
    textStyle: "on a rustic hand-painted wooden sign hanging with pink bougainvillea flowers" },
  { id: "dubrovnik", name: "Dubrovnik", country: "Croatia", emoji: "🏰", region: "Mediterranean",
    categories: ["couple"],
    promptHint: "pearl of the Adriatic, Dubrovnik Croatia, medieval city walls glowing orange at sunset, terracotta rooftops, crystal clear Adriatic Sea",
    textStyle: "carved into the ancient limestone city wall in elegant lettering" },
  { id: "malta-lagoon", name: "Blue Lagoon", country: "Malta", emoji: "💎", region: "Mediterranean",
    categories: ["couple"],
    promptHint: "crystal clear azure Blue Lagoon of Comino, Malta, shallow turquoise water, limestone cliffs, luxury sailboats, pristine white sand",
    textStyle: "written in pebbles and shells on the white sandy shore" },
  { id: "monaco", name: "Monaco Coastline", country: "Monaco", emoji: "🎰", region: "Mediterranean",
    categories: ["couple", "birthday"],
    promptHint: "glamorous Monaco coastline at night, superyachts in the harbor, glittering city lights reflecting on the water, dramatic cliffs, luxury architecture",
    textStyle: "on a glowing golden neon sign at the harbor casino entrance" },

  // ── Americas ───────────────────────────────────────────────────────────────
  { id: "monument-valley", name: "Monument Valley", country: "USA", emoji: "🏜️", region: "Americas",
    categories: ["couple", "pet"],
    promptHint: "iconic Monument Valley, Arizona USA, towering red sandstone buttes and mesas rising from the desert floor, dramatic golden hour sky with purple clouds, vast silence",
    textStyle: "on a weathered wooden signpost standing in the desert sand" },
  { id: "grand-canyon", name: "Grand Canyon", country: "USA", emoji: "🌄", region: "Americas",
    categories: ["couple", "birthday", "pet"],
    promptHint: "breathtaking Grand Canyon at golden hour, layered red rock formations carved by the Colorado River, sweeping vistas, vivid sunset clouds, ancient geological wonder",
    textStyle: "written in glowing golden letters across the dramatic sunset sky" },
  { id: "antelope-canyon", name: "Antelope Canyon", country: "USA", emoji: "🌀", region: "Americas",
    categories: ["couple", "birthday"],
    promptHint: "mystical Antelope Canyon, Arizona, narrow flowing sandstone walls glowing in shades of orange, red and purple, magical light beams filtering from above",
    textStyle: "etched into the glowing sandstone wall illuminated by a magical light beam from above" },
  { id: "machu-picchu", name: "Machu Picchu", country: "Peru", emoji: "🏔️", region: "Americas",
    categories: ["couple"],
    promptHint: "ancient Inca citadel of Machu Picchu, Peru, shrouded in morning mist, dramatic Andes mountains, lush green valleys below, mysterious and majestic",
    textStyle: "carved into an ancient Inca stone tablet among the ruins" },
  { id: "patagonia", name: "Patagonia", country: "Argentina", emoji: "🧊", region: "Americas",
    categories: ["couple", "pet"],
    promptHint: "dramatic Patagonia wilderness, Argentina, jagged granite peaks of Torres del Paine reflected in mirror-clear glacier lakes, pristine wild landscape",
    textStyle: "on a vintage wooden trail signpost in the wilderness" },
  { id: "banff", name: "Lake Louise", country: "Canada", emoji: "🍁", region: "Americas",
    categories: ["couple", "birthday", "pet"],
    promptHint: "fairytale Lake Louise, Banff National Park Canada, turquoise glacial water reflecting snow-capped Rocky Mountains, autumn foliage, Chateau hotel",
    textStyle: "written in the fresh mountain snow on the frozen lake shore" },
  { id: "havana", name: "Havana", country: "Cuba", emoji: "🎺", region: "Americas",
    categories: ["couple", "birthday"],
    promptHint: "colorful streets of old Havana, Cuba, vintage American cars, pastel colonial buildings, salsa rhythms in the air, warm tropical evening light",
    textStyle: "on a vibrant retro neon sign above a pastel colonial building" },
  { id: "rio", name: "Rio de Janeiro", country: "Brazil", emoji: "🇧🇷", region: "Americas",
    categories: ["birthday"],
    promptHint: "iconic Rio de Janeiro, Brazil, Copacabana beach with Sugarloaf Mountain, Christ the Redeemer statue, vibrant Carnival atmosphere, tropical lush mountains",
    textStyle: "written in lights on a spectacular illuminated Carnival float" },
  { id: "caribbean", name: "Caribbean Beach", country: "Caribbean", emoji: "🌴", region: "Americas",
    categories: ["couple", "birthday", "pet"],
    promptHint: "paradise Caribbean beach, powder white sand, impossibly clear shallow turquoise water, swaying palm trees, hammock between palms, endless blue sky",
    textStyle: "written with seashells and tropical flowers on the pristine white sand beach" },
  { id: "yosemite", name: "Yosemite Valley", country: "USA", emoji: "🌲", region: "Americas",
    categories: ["couple", "pet"],
    promptHint: "majestic Yosemite Valley, California, Half Dome reflecting in Mirror Lake, towering ancient sequoia trees, dramatic granite cliffs, Yosemite Falls mist",
    textStyle: "carved on a rustic wooden park ranger sign among towering sequoia trees" },

  // ── Asia Pacific ───────────────────────────────────────────────────────────
  { id: "bali-rice", name: "Bali Rice Terraces", country: "Indonesia", emoji: "🌾", region: "Asia Pacific",
    categories: ["couple", "pet"],
    promptHint: "lush emerald green rice terraces of Tegalalang, Bali Indonesia, layered curved paddy fields reflecting morning light, tropical jungle, sacred atmosphere",
    textStyle: "on a carved wooden Balinese offering signpost decorated with tropical flowers" },
  { id: "kyoto-cherry", name: "Kyoto Cherry Blossoms", country: "Japan", emoji: "🌸", region: "Asia Pacific",
    categories: ["couple", "birthday", "pet"],
    promptHint: "ethereal cherry blossom season in Kyoto, Japan, sakura petals falling like pink snow, ancient wooden temples, stone lanterns, peaceful garden paths",
    textStyle: "on a traditional Japanese paper lantern glowing softly among cherry blossom branches" },
  { id: "tokyo-skyline", name: "Tokyo Skyline", country: "Japan", emoji: "🗼", region: "Asia Pacific",
    categories: ["birthday"],
    promptHint: "dazzling Tokyo skyline at night with Mount Fuji silhouette, neon lights reflecting on glass towers, Tokyo Tower glowing red, vibrant metropolis energy",
    textStyle: "on a giant glowing neon billboard in the dazzling Tokyo skyline" },
  { id: "maldives", name: "Maldives Overwater", country: "Maldives", emoji: "🏝️", region: "Asia Pacific",
    categories: ["couple", "birthday"],
    promptHint: "luxury overwater bungalow in the Maldives, infinite turquoise Indian Ocean, perfect coral reef visible below, dramatic tropical sunset, pure paradise",
    textStyle: "written in tropical flower petals arranged on the overwater bungalow deck" },
  { id: "phi-phi", name: "Phi Phi Islands", country: "Thailand", emoji: "🐠", region: "Asia Pacific",
    categories: ["couple", "pet"],
    promptHint: "stunning Phi Phi Islands, Thailand, dramatic limestone karsts rising from emerald green water, Maya Bay white sand beach, tropical paradise",
    textStyle: "written in the white sand of the bay with seashells and palm leaves" },
  { id: "halong-bay", name: "Ha Long Bay", country: "Vietnam", emoji: "⛵", region: "Asia Pacific",
    categories: ["couple", "pet"],
    promptHint: "mystical Ha Long Bay, Vietnam, thousands of limestone karst islands rising from emerald waters, traditional wooden junk boats, misty morning atmosphere",
    textStyle: "painted on a hand-carved wooden plank hung from a traditional junk boat" },
  { id: "angkor-wat", name: "Angkor Wat", country: "Cambodia", emoji: "🛕", region: "Asia Pacific",
    categories: ["couple"],
    promptHint: "ancient Angkor Wat temple complex, Cambodia, reflected perfectly in moat at sunrise, lotus flowers, ancient khmer stone carvings, jungle vines, golden light",
    textStyle: "carved into the ancient Khmer stone temple wall in decorative script" },
  { id: "bora-bora", name: "Bora Bora", country: "French Polynesia", emoji: "🌺", region: "Asia Pacific",
    categories: ["couple", "birthday"],
    promptHint: "dreamy Bora Bora, French Polynesia, Mount Otemanu reflected in crystal lagoon, turquoise coral reef, overwater bungalows, untouched tropical beauty",
    textStyle: "on a hand-painted wooden sign at the overwater bungalow dock decorated with hibiscus flowers" },
  { id: "whitsundays", name: "Whitsunday Islands", country: "Australia", emoji: "🦈", region: "Asia Pacific",
    categories: ["couple", "pet"],
    promptHint: "Whitehaven Beach, Whitsunday Islands Australia, swirling silica sand and turquoise water from Hill Inlet lookout, pristine Great Barrier Reef, azure sky",
    textStyle: "written in large letters in the swirling white silica sand visible from above" },
  { id: "new-zealand", name: "NZ Fjords", country: "New Zealand", emoji: "🦅", region: "Asia Pacific",
    categories: ["couple", "pet"],
    promptHint: "dramatic Milford Sound fjord, New Zealand, Mitre Peak reflection in still waters, cascading waterfalls, ancient rainforest, dolphins playing",
    textStyle: "on a vintage hand-painted wooden signpost beside the still fjord waters" },

  // ── Middle East ────────────────────────────────────────────────────────────
  { id: "dubai-desert", name: "Dubai Desert", country: "UAE", emoji: "🐪", region: "Middle East",
    categories: ["couple", "pet"],
    promptHint: "golden dunes of Dubai desert at sunset, UAE, rippling sand patterns, camel silhouettes, dramatic orange sky, Dubai skyline glittering in the distance",
    textStyle: "written in sweeping Arabic calligraphy style in the golden sand dunes" },
  { id: "petra", name: "Petra", country: "Jordan", emoji: "🏛️", region: "Middle East",
    categories: ["couple"],
    promptHint: "ancient rose-red city of Petra, Jordan, Treasury building carved into sandstone cliffs glowing at sunset, Bedouin trader, candles lighting the Siq at night",
    textStyle: "carved into the rose-red sandstone cliff wall in ancient-style lettering" },
  { id: "dead-sea", name: "Dead Sea", country: "Jordan/Israel", emoji: "🌊", region: "Middle East",
    categories: ["couple"],
    promptHint: "surreal Dead Sea, lowest point on Earth, ultra-salty water with perfect reflection of orange sky, white mineral salt crusts, Judean Hills in the distance",
    textStyle: "written in white mineral salt crystals arranged on the crystalline shore" },
  { id: "wadi-rum", name: "Wadi Rum", country: "Jordan", emoji: "🚀", region: "Middle East",
    categories: ["couple", "pet"],
    promptHint: "alien landscape of Wadi Rum, Jordan, dramatic red sandstone rock formations under a Milky Way galaxy sky, Bedouin camp fire glow, Mars-like valley",
    textStyle: "written in glowing star letters across the breathtaking Milky Way night sky" },
  { id: "muscat", name: "Muscat", country: "Oman", emoji: "🕌", region: "Middle East",
    categories: ["couple"],
    promptHint: "Grand Mosque of Muscat, Oman, gleaming white marble architecture reflecting golden sunset light, ornate geometric patterns, date palms, dramatic mountain backdrop",
    textStyle: "in ornate Arabic calligraphy on the gleaming white marble wall of the mosque" },

  // ── Africa ─────────────────────────────────────────────────────────────────
  { id: "sahara", name: "Sahara Desert", country: "Morocco", emoji: "🌅", region: "Africa",
    categories: ["couple", "pet"],
    promptHint: "vast rolling dunes of the Sahara Desert at sunset, Morocco, golden sand sculpted by wind, lone camel caravan silhouette, spectacular red-orange sky, star-lit night",
    textStyle: "written in large sweeping letters across the golden sand dunes" },
  { id: "masai-mara", name: "Masai Mara Safari", country: "Kenya", emoji: "🦁", region: "Africa",
    categories: ["birthday", "pet"],
    promptHint: "African safari at golden hour, Masai Mara Kenya, acacia tree silhouette against vivid orange sunset, wildebeest migration, majestic lions, vast savannah",
    textStyle: "on a rustic hand-painted wooden safari camp sign under an acacia tree" },
  { id: "victoria-falls", name: "Victoria Falls", country: "Zimbabwe", emoji: "💧", region: "Africa",
    categories: ["couple", "birthday", "pet"],
    promptHint: "thundering Victoria Falls, Zimbabwe, world's largest waterfall, massive rainbow over the gorge, dense rainforest mist, Zambezi River power and majesty",
    textStyle: "written in glowing letters within the rainbow arc above the thundering waterfall" },
  { id: "zanzibar", name: "Zanzibar Beach", country: "Tanzania", emoji: "🐚", region: "Africa",
    categories: ["couple", "pet"],
    promptHint: "pristine Zanzibar beach, Tanzania, turquoise Indian Ocean, traditional dhow sailing boat at sunset, white sand with starfish, swaying coconut palms",
    textStyle: "written with starfish and tropical shells on the pure white sand beach" },
  { id: "cape-town", name: "Cape Town", country: "South Africa", emoji: "🏔️", region: "Africa",
    categories: ["birthday", "pet"],
    promptHint: "dramatic Cape Town, South Africa, Table Mountain flat-topped summit above the city, Camps Bay beach with boulder-sized rocks, Atlantic Ocean, vibrant sunset colors",
    textStyle: "on a colorful hand-painted mural on a Bo-Kaap neighborhood wall" },

  // ── Europe ─────────────────────────────────────────────────────────────────
  { id: "swiss-alps", name: "Swiss Alps", country: "Switzerland", emoji: "🏔️", region: "Europe",
    categories: ["couple", "birthday", "pet"],
    promptHint: "breathtaking Swiss Alps, snow-capped Matterhorn peak reflected in Riffelsee lake, wildflower meadows in bloom, traditional wooden chalet, crisp mountain air",
    textStyle: "written in the fresh powder snow on the mountain slope beside the chalet" },
  { id: "tulip-fields", name: "Tulip Fields", country: "Netherlands", emoji: "🌷", region: "Europe",
    categories: ["birthday", "pet"],
    promptHint: "endless colorful tulip fields of the Netherlands, vibrant stripes of red, pink, yellow, purple blooms stretching to horizon, classic Dutch windmill, blue sky",
    textStyle: "on a classic Dutch painted wooden sign beside the windmill among the tulips" },
  { id: "paris", name: "Paris by Night", country: "France", emoji: "🗼", region: "Europe",
    categories: ["couple", "birthday"],
    promptHint: "romantic Paris at night, Eiffel Tower sparkling with golden lights reflected on the Seine River, lovers on Pont des Arts, Parisian cafes glowing, moonlit sky",
    textStyle: "written in sparkling golden lights on the illuminated Eiffel Tower" },
  { id: "northern-lights", name: "Northern Lights", country: "Iceland", emoji: "✨", region: "Europe",
    categories: ["couple", "birthday"],
    promptHint: "spectacular aurora borealis dancing over Iceland, vivid green and purple curtains of northern lights reflected in volcanic lake, snow-covered landscape, infinite night sky",
    textStyle: "written in glowing aurora letters dancing in the northern lights sky" },
  { id: "scottish-highlands", name: "Scottish Highlands", country: "Scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", region: "Europe",
    categories: ["couple", "pet"],
    promptHint: "wild Scottish Highlands, dramatic misty glens and lochs, ancient stone castle ruins, purple heather moors, dramatic storm clouds, ancient mystical atmosphere",
    textStyle: "carved into an ancient Celtic standing stone among the purple heather moors" },
  { id: "prague", name: "Prague Old Town", country: "Czech Republic", emoji: "🏰", region: "Europe",
    categories: ["couple", "birthday"],
    promptHint: "fairytale Prague Old Town at dusk, Gothic spires and medieval towers reflected in the Vltava River, cobblestone Charles Bridge with saints statues, warm glowing lanterns",
    textStyle: "on a vintage hand-painted shop sign hanging in the glowing old town square" },
  { id: "venice", name: "Venice Canals", country: "Italy", emoji: "🚣", region: "Europe",
    categories: ["couple", "birthday"],
    promptHint: "enchanting Venice at golden hour, gondola gliding through narrow canal, Renaissance palazzos reflecting in water, stone bridges draped in flowers, magical light",
    textStyle: "painted in gold script on the side of a decorated gondola" },
  { id: "lisbon", name: "Lisbon Sunset", country: "Portugal", emoji: "🎸", region: "Europe",
    categories: ["couple", "birthday"],
    promptHint: "golden Lisbon at sunset, Portugal, colorful azulejo tile buildings, tram climbing cobbled hill, Rio Tejo estuary glowing orange, viewpoints with magnificent vistas",
    textStyle: "in beautiful hand-painted blue-and-white azulejo ceramic tiles on a wall" },
  { id: "tuscany", name: "Tuscany Vineyards", country: "Italy", emoji: "🍷", region: "Europe",
    categories: ["couple", "birthday", "pet"],
    promptHint: "romantic Tuscany landscape, Italy, rolling golden hills with cypress trees lining a winding road, ancient farmhouse, vineyards at harvest, warm amber afternoon light",
    textStyle: "on a vintage hand-painted wine label on a rustic wooden barrel at the vineyard" },
  { id: "provence", name: "Lavender Fields", country: "France", emoji: "💜", region: "Europe",
    categories: ["couple", "birthday", "pet"],
    promptHint: "dreamy lavender fields of Provence, France, endless purple rows stretching to horizon, stone farmhouse, golden light, bumble bees, fragrant summer beauty",
    textStyle: "on a rustic painted wooden lavender farm sign among the purple blooms" },
];

export const AI_LOCATION_REGIONS = ["Mediterranean", "Americas", "Asia Pacific", "Middle East", "Africa", "Europe"];

export function getLocationsForCategory(category: CardCategory): AiLocation[] {
  return AI_LOCATIONS.filter(l => l.categories.includes(category));
}
